### ISSUE TITLE
java.net.ProtocolException: Too many follow-up requests: 21

### ISSUE THREAD

**Issue by PeelDroid** [rburgst/okhttp-digest#1] opened 2015-11-03 01:01 UTC
Hi, I'm trying out your lib w/ latest Android SDK M and trying a http digest authentication web service returns me: java.net.ProtocolException: Too many follow-up requests: 21

I used your sample code:
OkHttpClient client = new OkHttpClient();
            final DigestAuthenticator authenticator = new DigestAuthenticator(new Credentials(username, password));

            final Map<String, CachingAuthenticator> authCache = new ConcurrentHashMap<>();
            client.interceptors().add(new AuthenticationCacheInterceptor(authCache));
            client.setAuthenticator(new CachingAuthenticatorDecorator(authenticator, authCache));

            Request request = new Request.Builder()
                    .url(url).get().build();
            Response response = client.newCall(request).execute();

Have you run into such an issue?

**Comment by rburgst** [comment] 2015-11-03 05:10
not yet, can you add the following code to your OkHttp client setup and see what it is doing?

        final HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor();
        httpLoggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        client.networkInterceptors().add(httpLoggingInterceptor);

If you mask the authentication stuff, then you can also post it here, so I can have a look.

**Comment by lexius** [comment] 2015-12-08 10:36
```
12-08 11:30:51.413 15384-16299/apps.android.camcontroller D/apps.android.camcontroller.net.interceptors.LoggingInterceptor: Sending request https://192.168.10.20/ISAPI/Streaming/status on Connection{192.168.10.20:443, proxy=DIRECT@ hostAddress=192.168.10.20 cipherSuite=TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
                                                                                                                            Host: 192.168.10.20
                                                                                                                            Connection: Keep-Alive
                                                                                                                            Accept-Encoding: gzip
                                                                                                                            User-Agent: okhttp/2.6.0
12-08 11:30:51.427 15384-16299/apps.android.camcontroller D/apps.android.camcontroller.net.interceptors.LoggingInterceptor: Received response for https://192.168.10.20/ISAPI/Streaming/status in 13,6ms
                                                                                                                            Date: Tue, 08 Dec 2015 11:30:51 GMT
                                                                                                                            Server: DNVRS-Webs
                                                                                                                            Cache-Control: no-cache
                                                                                                                            Content-Length: 125
                                                                                                                            Content-Type: application/xml; charset="UTF-8"
                                                                                                                            Connection: keep-alive
                                                                                                                            Keep-Alive: timeout=60, max=99
                                                                                                                            WWW-Authenticate: Digest realm="DVRNVRDVS", domain="httpsHost", qop="auth", nonce="92dbc7ef487a9f091bbe2ad1726906b8:1449574251244", opaque="", algorithm="MD5", stale="FALSE"
                                                                                                                            WWW-Authenticate: Basic realm="DVRNVRDVS"
                                                                                                                            OkHttp-Selected-Protocol: http/1.1
                                                                                                                            OkHttp-Sent-Millis: 1449570651413
                                                                                                                            OkHttp-Received-Millis: 1449570651427
12-08 11:30:51.428 15384-16299/apps.android.camcontroller D/Retrofit: ---- ERROR https://192.168.10.20:443/ISAPI/Streaming/status
12-08 11:30:51.443 15384-16299/apps.android.camcontroller D/Retrofit: java.lang.IllegalArgumentException: unsupported auth scheme: Basic realm="DVRNVRDVS"
                                                                          at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticate(DigestAuthenticator.java:147)
                                                                          at com.burgstaller.okhttp.DispatchingAuthenticator.authenticate(DispatchingAuthenticator.java:42)
                                                                          at com.burgstaller.okhttp.CachingAuthenticatorDecorator.authenticate(CachingAuthenticatorDecorator.java:28)
                                                                          at com.squareup.okhttp.internal.http.OkHeaders.processAuthHeader(OkHeaders.java:285)
                                                                          at com.squareup.okhttp.internal.http.HttpEngine.followUpRequest(HttpEngine.java:1068)
                                                                          at com.squareup.okhttp.Call.getResponse(Call.java:303)
                                                                          at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
                                                                          at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:40)
                                                                          at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:223)
                                                                          at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
                                                                          at com.squareup.okhttp.Call.execute(Call.java:79)
                                                                          at retrofit.client.OkClient.execute(OkClient.java:53)
                                                                          at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                                                                          at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
                                                                          at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                          at $Proxy12.getStreamingStatus(Unknown Source)
                                                                          at apps.android.camcontroller.net.RetrieveHikvisionStatus.doInBackground(RetrieveHikvisionStatus.java:76)
                                                                          at apps.android.camcontroller.net.RetrieveHikvisionStatus.doInBackground(RetrieveHikvisionStatus.java:22)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
12-08 11:30:51.443 15384-16299/apps.android.camcontroller D/Retrofit: ---- END ERROR
```

Possible solution:

DigestAuthenticator.java
```
@Override
    public Request authenticate(Proxy proxy, Response response) throws IOException {
        //my modification
        //String header = response.header("WWW-Authenticate");
        List<String> headers = response.headers("WWW-Authenticate");
        String header = null;
        for (String value : headers) {
            header = header!= null ? header + " " + value : value;
        }
        if (!header.contains("Digest")) {
            throw new IllegalArgumentException("unsupported auth scheme: " + header);
        }
        parseChallenge(header, 7, header.length() - 7);
        // first copy all request headers to our params array
        copyHeaderMap(response.headers(), parameters);

        return  authenticateWithState(response.request());
    }
```

**Comment by rburgst** [comment] 2015-12-09 07:54
Seems like this might be caused by the lastest changes in okhttp-2.6.0. Need to investigate further.

**Comment by rburgst** [comment] 2016-04-19 04:30
this should be fixed in the latest version.

**Closed by rburgst** 2016-04-19 04:30 UTC

**Comment by crgpww** [comment] 2016-06-01 00:42
Hi @rburgst , I'm facing the exactly the same issue using the sample and version 1.5 (OkHttp version is 3.3.1). Any idea?
