### ISSUE TITLE
Proxy Digest Authentication

### ISSUE THREAD

**Issue by mopsop** [rburgst/okhttp-digest#9] opened 2016-04-18 13:36 UTC
Hi,
I try to use okhhtp-digest for proxy authentication so I set proxy attribute to true.
But in findDigestHeader() method the "WWW-Authenticate" header is used instead of testing the proxy attribute and using WWW_AUTH or PROXY_AUTH constants.

Even after this change, the authentication fails :( The proxy-Authorization header is generated but refused by the proxy. And the mechanism to prevent infinite loops does not work also because of wrong header name used.

Here is the Proxy Authenticator I use : 

```
public class ProxyDigestAuthenticator extends DigestAuthenticator {

    public ProxyDigestAuthenticator(Credentials credentials) {
        super(credentials);
        setProxy(true);
    }

    @Override
    public Request authenticate(Route route, Response response) throws IOException {

        if(response.request().header(PROXY_AUTH_RESP) != null)
            return null;


        String header = findProxyDigestHeader(response);
        parseChallenge(header, 7, header.length() - 7);
        // first copy all request headers to our params array
        copyHeaderMap(response.headers(), parameters);

        return authenticateWithState(response.request());
    }

    private String findProxyDigestHeader(Response response) {
        final List<String> headers = response.headers(PROXY_AUTH);
        for (String header : headers) {
            if (header.startsWith("Digest")) {
                return header;
            }
        }
        throw new IllegalArgumentException("unsupported auth scheme: " + headers);
    }


    private void copyHeaderMap(Headers headers, Map<String, String> dest) {
        for (int i = 0; i < headers.size(); i++) {
            dest.put(headers.name(i), headers.value(i));
        }
    }

}

```

And how it is used : 

```
        final ProxyDigestAuthenticator authenticator = new ProxyDigestAuthenticator(new Credentials("proxy_user", "proxy_pass"));
        builder.proxyAuthenticator(authenticator);

        final Map<String, CachingAuthenticator> authCache = new ConcurrentHashMap<>();
        builder.addInterceptor(new AuthenticationCacheInterceptor(authCache));
        builder.authenticator(new CachingAuthenticatorDecorator(authenticator, authCache));        
        OkHttpClient client = builder.build();


        Request request = new Request.Builder()
                .url("https://mySite.com")
                .build();

    Response response = client.newCall(request).execute();

```

Any idea why it fails with these changes ?

Thanks

**Comment by rburgst** [comment] 2016-04-19 04:30
Sorry, I don't really have experience nor the means to test proxy authentication. The basic authenticator is quite a straight port of Apache HttpClient. You might want to take a look at https://github.com/apache/httpclient/blob/4.3.x/httpclient/src/main/java/org/apache/http/impl/auth/DigestScheme.java and see if you can make it work.

**Comment by mopsop** [comment] 2016-04-20 14:37
I use Squid to test it

**Comment by mopsop** [comment] 2016-04-25 13:24
The issue is with HTTPS, the method name is CONNECT instead of the method from the request to the final server. So I changed in DigestAuthenticator.authenticateWithState() : 
```
        final String uri = request.url().toString();
       	getParameters().put("methodname", method);

```
with
```
        final String uri = request.url().toString();
        if("https".equals(request.url().scheme()))
        	getParameters().put("methodname", "CONNECT");
        else
        	getParameters().put("methodname", method);

```

**Comment by rburgst** [comment] 2016-04-27 03:39
I am not sure this solution is the correct one. If you check The before mentioned apache HC you see that its sending a different authorization header (`Proxy-Authorization`  instead of  `Authorization`).

See https://github.com/apache/httpclient/blob/4.3.x/httpclient/src/main/java/org/apache/http/impl/auth/DigestScheme.java#L396
and https://github.com/apache/httpclient/blob/4.3.x/httpclient/src/main/java/org/apache/http/auth/AUTH.java

The fact that your approach works in your specific case is good but it doesn't make me feel confident that it would work in all situations.

**Comment by mopsop** [comment] 2016-05-11 06:57
Yes, you have also to change the authorization header, it's what I tried to describe in my first post in the thread

**Comment by jrichardBD** [comment] 2016-12-07 16:47
I agree, in https://github.com/rburgst/okhttp-digest/blob/master/src/main/java/com/burgstaller/okhttp/digest/DigestAuthenticator.java findDigestHeader(Headers headers) should look for more than just the header WWW-Authenticate.  For proxies you should be looking for the header Proxy-Authenticate.

**Comment by rburgst** [comment] 2016-12-20 05:03
I checked in a couple of changes that might improve the situation, can someone test if this is enough?

**Comment by Kudo** [comment] 2017-01-10 02:27
I faced this issue over HTTP tunnel today from latest master branch code and unfortunately not works.
The root cause is same as @mopsop mentioned for the HTTP method.
Besides, the uri should be `host:port`.

Following POC is from my fix (but not for okhttp-digest as authenticateWithState don't pass Route)
```java
    if (route.requiresTunnel()) {
      method = "CONNECT";
      uri = request.url().host() + ':' + request.url().port();
    } else {
      method = request.method();
      uri = request.url().uri().getPath();
    }
```

**Comment by rburgst** [comment] 2017-01-11 22:28
Without a setup to test this is very hard for me to fix. @Kudo or @mopsop can you provide a test server + account so I can try? Sample code would obviously help tremendously.

**Comment by rburgst** [comment] 2017-01-11 22:43
I have added the route to `authenticateWithState`, @Kudo  can you give it a try to see whether you can make it work?

**Comment by Kudo** [comment] 2017-01-13 04:06
@rburgst Thanks for passing route to authenticateWithState() and it did works after #27 changes.
For test proxy server, please let me email you privately.

**Closed** 2017-01-13 05:42 UTC
